### ISSUE TITLE
Error: failed to download

### ISSUE THREAD

**Issue by LpmRaven** [robinmetral/gatsby-source-s3#19]
Hi @robinmetral, I am getting the error for every image: 

```
 ERROR 

failed to process https://s3.us-east-1.amazonaws.com/<redacted bucketname>/FAJKCAN20001-gold-1.jpg
Failed to download https://s3.us-east-1.amazonaws.com/<redacted bucketname>/FAJKCAN20001-gold-1.jpg after 3 attempts

``` 

Do you have any ideas about why this might be? I also think you have an issue with the plugin as it crashed my terminal and mac (after about 200+ of these errors), it does not end.

My first thought is that this is a permissions issue on the S3 bucket, but I am using the following cloudformation which grants public access:

```yaml
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "<redacted bucketname>"
      AccessControl: PublicRead
    DeletionPolicy: Retain

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Join ["", [!GetAtt ImagesBucket.Arn, "/*"]]
      Bucket: !Ref ImagesBucket
```

I've also granted `AmazonS3ReadOnlyAccess` for programmatic access to the user of the accessKeyId.

```js
{
  resolve: `@robinmetral/gatsby-source-s3`,
  options: {
      aws: {
          accessKeyId: process.env.GATSBY_SOURCE_S3_IMAGE_KEY_ID,
          secretAccessKey: process.env.GATSBY_SOURCE_S3_IMAGE_KEY_SECRET,
          region: 'us-east-1'
      },
      buckets: ["<redacted bucketname>"]
  }
},
```
